# Generated by Django 5.1.1 on 2024-09-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=254716394611, max_length=15),
            preserve_default=False,
        ),
    ]
