name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  

    - name: Install AWS CLI 
      run: |
        sudo apt-get install -y unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          pip install -r requirements.txt
        else
      # Remove pywin32 from requirements.txt for non-Windows runners
          sed -i '/pywin32/d' requirements.txt
          pip install -r requirements.txt
        fi
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
        EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}

    - name: Install Elastic Beanstalk CLI
      run: |
        sudo apt-get update && sudo apt-get install -y python3-pip
        pip3 install awsebcli

    - name: Initialize Elastic Beanstalk (if needed)
      run: |
        eb init -p python-3.11 ${{ secrets.EB_APP_NAME }} --region us-east-1
        eb use ${{ secrets.EB_ENV_NAME }}

    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy
  # zip -r customerservice-app.zip .  # Zip the application files
  # aws elasticbeanstalk create-application-version \
  #   --application-name ${{ secrets.EB_APP_NAME }} \
  #   --version-label v1 \
  #   --source-bundle S3Bucket=customerservice-app,S3Key=customerservice-app.zip
  # aws elasticbeanstalk update-environment \
  #   --application-name ${{ secrets.EB_APP_NAME }} \
  #   --environment-name ${{ secrets.EB_ENV_NAME }} \
  #   --version-label v1
